### ISSUE TITLE
Out of Bounds

### ISSUE THREAD

**Issue by vogtl19** [upcs/cs-341-project-sq19-india#24]
Recreate: 
1. Click earthquake (the rectangle for tornado is still selected, also an issue)
2. Click outside in Idaho or something
3. Click submit
4. Nothing happens. I would recommend the user gets notified that they are out of bounds (I think you did that earlier).

**Comment by devins98** [comment]
We will add some kind of alert or way to notify the user.

**Comment by devins98** [comment]
Added an alert
