### ISSUE TITLE
Coordinates (0, 0) give false info and no error

### ISSUE THREAD

**Issue by crawforl20** [upcs/cs-341-project-sq19-india#34]
It was mentioned that manually typing large fields into the inputs doesn't give an error but yields results as all zero's. However, if the user manually inputs (0, 0) in each of the input fields, no error is reported as outside Portland region, and a default 1 is given in the fields of Market, Police, Tier One.

Steps to reproduce:
1. type '0' into each of the input coordinates fields.
2. click submit. (under any disaster, the result is the same).
3. Results => Market: 1 Police: 1 Tier One: 1

**Comment by chrisfishback** [comment]
can't input coordinates anymore
